/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "velopera.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x321_CCVS1(can_obj_velopera_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Speed: start-bit 0, length 10, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x321_CCVS1.Speed)) & 0x3ff;
	i |= x;
	/* Gear: start-bit 10, length 3, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x321_CCVS1.Gear)) & 0x7;
	x <<= 10; 
	i |= x;
	*data = (i);
	o->can_0x321_CCVS1_tx = 1;
	return 8;
}

static int unpack_can_0x321_CCVS1(can_obj_velopera_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Speed: start-bit 0, length 10, endianess intel, scaling 0.1, offset 0 */
	x = i & 0x3ff;
	o->can_0x321_CCVS1.Speed = x;
	/* Gear: start-bit 10, length 3, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x7;
	o->can_0x321_CCVS1.Gear = x;
	o->can_0x321_CCVS1_rx = 1;
	o->can_0x321_CCVS1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x321_Speed(const can_obj_velopera_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x321_CCVS1.Speed);
	rval *= 0.1;
	if (rval <= 200) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x321_Speed(can_obj_velopera_h_t *o, double in) {
	assert(o);
	o->can_0x321_CCVS1.Speed = 0;
	if (in > 200)
		return -1;
	in *= 10;
	o->can_0x321_CCVS1.Speed = in;
	return 0;
}

int decode_can_0x321_Gear(const can_obj_velopera_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x321_CCVS1.Gear);
	*out = rval;
	return 0;
}

int encode_can_0x321_Gear(can_obj_velopera_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x321_CCVS1.Gear = in;
	return 0;
}

int print_can_0x321_CCVS1(const can_obj_velopera_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Speed = (wire: %.0f)\n", (double)(o->can_0x321_CCVS1.Speed)));
	r = print_helper(r, fprintf(output, "Gear = (wire: %.0f)\n", (double)(o->can_0x321_CCVS1.Gear)));
	return r;
}

static int pack_can_0x322_COMPASS(can_obj_velopera_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Heading: start-bit 0, length 9, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x322_COMPASS.Heading)) & 0x1ff;
	i |= x;
	*data = (i);
	o->can_0x322_COMPASS_tx = 1;
	return 8;
}

static int unpack_can_0x322_COMPASS(can_obj_velopera_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Heading: start-bit 0, length 9, endianess intel, scaling 1, offset 0 */
	x = i & 0x1ff;
	o->can_0x322_COMPASS.Heading = x;
	o->can_0x322_COMPASS_rx = 1;
	o->can_0x322_COMPASS_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x322_Heading(const can_obj_velopera_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x322_COMPASS.Heading);
	if (rval <= 360) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16_t)0;
		return -1;
	}
}

int encode_can_0x322_Heading(can_obj_velopera_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x322_COMPASS.Heading = 0;
	if (in > 360)
		return -1;
	o->can_0x322_COMPASS.Heading = in;
	return 0;
}

int print_can_0x322_COMPASS(const can_obj_velopera_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Heading = (wire: %.0f)\n", (double)(o->can_0x322_COMPASS.Heading)));
	return r;
}

static int pack_can_0x323_ENVIRONMENT(can_obj_velopera_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Pressure: start-bit 15, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x323_ENVIRONMENT.Pressure)) & 0x3ff;
	x <<= 15; 
	i |= x;
	/* Temp: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x323_ENVIRONMENT.Temp)) & 0xff;
	i |= x;
	/* Humid: start-bit 8, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x323_ENVIRONMENT.Humid)) & 0x7f;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x323_ENVIRONMENT_tx = 1;
	return 8;
}

static int unpack_can_0x323_ENVIRONMENT(can_obj_velopera_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Pressure: start-bit 15, length 10, endianess intel, scaling 1, offset 0 */
	x = (i >> 15) & 0x3ff;
	o->can_0x323_ENVIRONMENT.Pressure = x;
	/* Temp: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x323_ENVIRONMENT.Temp = x;
	/* Humid: start-bit 8, length 7, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x7f;
	o->can_0x323_ENVIRONMENT.Humid = x;
	o->can_0x323_ENVIRONMENT_rx = 1;
	o->can_0x323_ENVIRONMENT_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x323_Pressure(const can_obj_velopera_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x323_ENVIRONMENT.Pressure);
	*out = rval;
	return 0;
}

int encode_can_0x323_Pressure(can_obj_velopera_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x323_ENVIRONMENT.Pressure = in;
	return 0;
}

int decode_can_0x323_Temp(const can_obj_velopera_h_t *o, int8_t *out) {
	assert(o);
	assert(out);
	int8_t rval = (int8_t)(o->can_0x323_ENVIRONMENT.Temp);
	if ((rval >= -30) && (rval <= 60)) {
		*out = rval;
		return 0;
	} else {
		*out = (int8_t)0;
		return -1;
	}
}

int encode_can_0x323_Temp(can_obj_velopera_h_t *o, int8_t in) {
	assert(o);
	o->can_0x323_ENVIRONMENT.Temp = 0;
	if (in < -30)
		return -1;
	if (in > 60)
		return -1;
	o->can_0x323_ENVIRONMENT.Temp = in;
	return 0;
}

int decode_can_0x323_Humid(const can_obj_velopera_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x323_ENVIRONMENT.Humid);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x323_Humid(can_obj_velopera_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x323_ENVIRONMENT.Humid = 0;
	if (in > 100)
		return -1;
	o->can_0x323_ENVIRONMENT.Humid = in;
	return 0;
}

int print_can_0x323_ENVIRONMENT(const can_obj_velopera_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Pressure = (wire: %.0f)\n", (double)(o->can_0x323_ENVIRONMENT.Pressure)));
	r = print_helper(r, fprintf(output, "Temp = (wire: %.0f)\n", (double)(o->can_0x323_ENVIRONMENT.Temp)));
	r = print_helper(r, fprintf(output, "Humid = (wire: %.0f)\n", (double)(o->can_0x323_ENVIRONMENT.Humid)));
	return r;
}

static int pack_can_0x324_NET(can_obj_velopera_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Status: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x324_NET.Status)) & 0xff;
	i |= x;
	*data = (i);
	o->can_0x324_NET_tx = 1;
	return 8;
}

static int unpack_can_0x324_NET(can_obj_velopera_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Status: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x324_NET.Status = x;
	o->can_0x324_NET_rx = 1;
	o->can_0x324_NET_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x324_Status(const can_obj_velopera_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x324_NET.Status);
	*out = rval;
	return 0;
}

int encode_can_0x324_Status(can_obj_velopera_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x324_NET.Status = in;
	return 0;
}

int print_can_0x324_NET(const can_obj_velopera_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Status = (wire: %.0f)\n", (double)(o->can_0x324_NET.Status)));
	return r;
}

int unpack_message(can_obj_velopera_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x321: return unpack_can_0x321_CCVS1(o, data, dlc, time_stamp);
	case 0x322: return unpack_can_0x322_COMPASS(o, data, dlc, time_stamp);
	case 0x323: return unpack_can_0x323_ENVIRONMENT(o, data, dlc, time_stamp);
	case 0x324: return unpack_can_0x324_NET(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_velopera_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x321: return pack_can_0x321_CCVS1(o, data);
	case 0x322: return pack_can_0x322_COMPASS(o, data);
	case 0x323: return pack_can_0x323_ENVIRONMENT(o, data);
	case 0x324: return pack_can_0x324_NET(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_velopera_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x321: return print_can_0x321_CCVS1(o, output);
	case 0x322: return print_can_0x322_COMPASS(o, output);
	case 0x323: return print_can_0x323_ENVIRONMENT(o, output);
	case 0x324: return print_can_0x324_NET(o, output);
	default: break; 
	}
	return -1; 
}

